# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo 测试，并部署您的项目。
vi .github/workflows/fork-sync.yml

name: Merge upstream branches

on:

  push:

  schedule:

     # actually, ~5 minutes is the highest

     # effective frequency you will get

    - cron:  '0 1 * * *'

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Merge upstream

        run: |

          git config --global user.name 'pangyichuan'

          git config --global user.email '1724494588@qq.com'

          # "git checkout master" is unnecessary, already here by default

          git pull --unshallow  # this option is very important, you would get

                                # complains about unrelated histories without it.

                                # (but actions/checkout@v2 can also be instructed

                                # to fetch all git depth right from the start)

          @添加上游仓库如果是其他上游仓库自行修改

		  git remote add upstream https://github.com/pangyichuan/faker2.git

          git fetch upstream

          # Neither forget the -b opt,

       
